name: coffee_tracker
description: A Flutter project to help track and reduce coffee intake.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  get_it: ^9.0.5

  # Utilities
  equatable: ^2.0.7
  dartz: ^0.10.1
  uuid: ^4.5.1
  intl: ^0.20.2
  geolocator: ^14.0.2

  # Networking & Security
  http: ^1.4.0
  http_interceptor: ^2.0.0
  http_parser: ^4.1.2
  connectivity_plus: ^7.0.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1

  # Local Storage & Auth
  shared_preferences: ^2.5.3
  local_auth: ^3.0.0

  # Media & Files
  image_picker: ^1.2.0
  image_cropper: ^11.0.0
  mime: ^2.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation & Testing
  build_runner: ^2.6.0
  mockito: ^5.4.6
  bloc_test: ^10.0.0

  # App Icon Generation
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/coffee_cup_outline.png
  #   - assets/images/steam.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
